### ISSUE TITLE
Moving from quick sqlite to the new op-sqlite

### ISSUE THREAD

**Issue by ducpt-bili** [powersync-ja/react-native-quick-sqlite#42]
Hi powersync team, op-sqlite is much faster and active maintain from the author.
I just want to ask, does it support underly by Powersync right now? or you are using quick-sqlite to decide to try Powersync.
Thanks

**Comment by ducpt-bili** [comment]
Btw, i just found this post:
https://www.powersync.com/blog/react-native-database-performance-comparison
Does it show us that Powersync is the best out there?

**Comment by rkistner** [comment]
As shown by those benchmarks, for most use cases the performance difference between the various options is not massive. There is a bit of gain in using JSI, which is the case for both op-sqlite and react-native-quick-sqlite. For general react-native use cases, I'd recommend op-sqlite.

Our fork of react-native-quick-sqlite here is generally to:
1. Add support for the PowerSync extension
2. Support multiple concurrent connections
3. Support update notifications

We'll likely move PowerSync over to op-sqlite in the future, since it seems like we'll be able to support all those without maintaining a separate fork.

**Comment by ducpt-bili** [comment]
hi @rkistner , i hope the move over will be process as soon as possible. 
Just one more question, when move to op-sqlite, our app will perform the same right?

**Comment by rkistner** [comment]
> hi @rkistner , i hope the move over will be process as soon as possible. Just one more question, when move to op-sqlite, our app will perform the same right?

Yes, we expect performance to be the same or perhaps slightly better on op-sqlite.

**Comment by ducpt-bili** [comment]
Hi @rkistner , one big feature i want to use is vector search, seem like PowerSync is not support it yet right?
Thanks.

**Comment by ducpt-bili** [comment]
hi @rkistner , i mean when i use old version sqlite of Powersync, then later when upgrade Powersync using new version (op-sqlite), does everything in our user mobile app will be work the same? Thanks

**Comment by rkistner** [comment]
Yes, it will continue using the same database file, and the PowerSync APIs will remain the same

**Comment by frankcalise** [comment]
Also in favor of this move to help support running with the new architecture

**Comment by rkistner** [comment]
We now have an alpha version of this available here:
https://github.com/powersync-ja/powersync-js/tree/main/packages/powersync-op-sqlite
